### PR TITLE
 CI pipeline

### PR DESCRIPTION
**Pull request by melezhik**
Hi! This pipeline works with current version of API. I have also added a CI badge.
An example report - https://ci.sparrowhub.io/report/2191

### CODE REVIEW

**Comment by bduggan** [comment]
excellent!

**Comment by melezhik** [comment]
👍

**Comment by bduggan** [comment]
hmm...the badge says "build unknown"

**Comment by melezhik** [comment]
Yeah , this is annoying GitHub caching issue -(  - https://github.com/melezhik/SparrowCI/issues/4#issuecomment-1347697476 , in this link you can find a work around

**Comment by melezhik** [comment]
Oh, no! Please never mind my previous comment , you need to add this repo to your repos list in your SparrowCI account to make the badge work …

**Comment by bduggan** [comment]
Great, added it (and updated the link with the new name of the repo).  looks good!

**Comment by melezhik** [comment]
Cool!

**Comment by melezhik** [comment]
The very first successful build - https://ci.sparrowhub.io/report/2225

**Pull request merged**
